/**
 * WorkspaceSnapshot
 *
 * A quiet companion to the README hero — a pinned notebook card, not a
 * dashboard. Reuses `Card`/`CardHeader`/`CardContent`
 * (components/ui/card.tsx) for structure rather than hand-rolling a new
 * bordered box, per AGENT.md's "extend an existing component before
 * creating a new one." Copy is entirely data-driven from
 * lib/constants/homepage-copy.ts's `WORKSPACE_SNAPSHOT_COPY` — adding a
 * fifth field later is a data change here, not a markup change.
 *
 * Deliberately excludes: charts, progress indicators, statistics, or any
 * animated widget — see docs/14-HOMEPAGE_COPY.md's Workspace Snapshot
 * "Notes" and Task 3.1 §9 ("act as supporting context. The README remains
 * the primary focus.").
 *
 * `<aside>` wraps `Card` (rather than `Card` itself becoming the aside) so
 * this stays a self-contained landmark distinct from the Sidebar's own
 * `<aside>` — `aria-labelledby` gives it an accessible name so screen
 * reader users can tell the two apart. A Server Component: static content,
 * no interactivity.
 */
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Stack } from "@/components/layout/stack";
import { WORKSPACE_SNAPSHOT_COPY } from "@/lib/constants/homepage-copy";

type SnapshotEntry = (typeof WORKSPACE_SNAPSHOT_COPY.entries)[number];

function SnapshotField({ entry }: { entry: SnapshotEntry }) {
  return (
    <div>
      <h3 className="text-caption text-muted-foreground">{entry.label}</h3>
      {"items" in entry ? (
        <ul className="mt-1.5 list-disc space-y-1 pl-4 text-small text-foreground">
          {entry.items.map((item) => (
            <li key={item}>{item}</li>
          ))}
        </ul>
      ) : (
        <p className="mt-1.5 text-small text-foreground">{entry.value}</p>
      )}
    </div>
  );
}

export function WorkspaceSnapshot() {
  return (
    <aside aria-labelledby="workspace-snapshot-heading">
      {/* Padding bumped from Card's default --card-spacing (1rem) to a
          plain px-6/py-6 (1.5rem) override, so the extra width from the
          wider grid track (see readme-hero.tsx) reads as a more generously
          breathing card, not just shorter wrapped lines. Overriding via a
          direct px-6/py-6 class — rather than reassigning the
          --card-spacing custom property — because tailwind-merge resolves
          a plain scale utility against Card/CardHeader/CardContent's own
          px-(--card-spacing) reliably; a same-property custom-value
          override needs the exact class regenerated by Tailwind's
          scanner, which is fine on a full build but was observed to lag
          behind on this repo's long-running Turbopack dev server. */}
      <Card className="py-6">
        <CardHeader className="px-6">
          <h2
            id="workspace-snapshot-heading"
            className="text-small font-medium text-foreground"
          >
            {WORKSPACE_SNAPSHOT_COPY.title}
          </h2>
        </CardHeader>
        <CardContent className="px-6">
          <Stack gap="md">
            {WORKSPACE_SNAPSHOT_COPY.entries.map((entry) => (
              <SnapshotField key={entry.label} entry={entry} />
            ))}
          </Stack>
        </CardContent>
      </Card>
    </aside>
  );
}
